name: Main

# see https://github.com/RodrigoDornelles/3bc-lang/blob/master/.github/workflows/automatic-publish.yaml

on:
  push:
    branches:
      - main

env:
  PROTOVERSION: '1.0'

jobs:
  publish_cdn:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go >=1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Run Tests
        if: ${{ !env.ACT }}
        run: go test -v $(go list ./... | grep -v /cmd | grep -v /runtime)
