name: Publish Release

on:
  release:
    types:
      - created

env:
  PROTOVERSION: '1.0'

jobs:
  publish_cdn:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go >=1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Run Tests
        if: ${{ !env.ACT }}
        run: go test -v $(go list ./... | grep -v /cmd | grep -v /runtime)
      - name: Set Tag
        id: vars
        run: |
          echo ::set-output name=TAG::$(git describe --tags)
      - name: Build
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          GO111MODULE=on CGO_ENABLED=0 GOOS=js GOARCH=wasm go build \
            -ldflags "-s -w -X github.com/elacity/crypto-protocol/core.Version=${{ env.PROTOVERSION }} -X github.com/elacity/crypto-protocol/core.Tag=${{ env.TAG }}" \
            -o ${{ github.workspace }}/artifact/crypto.protocol.wasm ./cmd/wasm/main.go
        env:
          TAG: ${{ steps.vars.outputs.TAG }}
      - name: Gzip
        run: |
          gzip -9 \
            -c ${{ github.workspace }}/artifact/crypto.protocol.wasm > ${{ github.workspace }}/artifact/crypto.protocol.wasm.gz
      - name: Publish to public repo
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: WAUIO/elacity-artifacts
        with:
          path: ${{ github.workspace }}/artifact/**
          if-no-files-found: error
