name: Publish Release

# see https://github.com/RodrigoDornelles/3bc-lang/blob/master/.github/workflows/automatic-publish.yaml

on:
  push:
    tags:
      - "*.*.*"

env:
  PROTOVERSION: "1.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go >=1.20
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run Tests
        if: ${{ !env.ACT }}
        run: go test -v $(go list ./... | grep -v /cmd | grep -v /runtime)
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Build
        run: |
          GO111MODULE=on CGO_ENABLED=0 GOOS=js GOARCH=wasm go build \
            -ldflags "-s -w -X github.com/elacity/crypto-protocol/core.Version=${{ env.PROTOVERSION }} -X github.com/elacity/crypto-protocol/core.Tag=${{ env.TAG }}" \
            -o ${{ github.workspace }}/output/crypto.protocol.wasm ./cmd/wasm/main.go
        env:
          TAG: ${{ steps.tag.outputs.tag }}
      - name: Gzip
        run: |
          gzip -9 \
            -c ${{ github.workspace }}/output/crypto.protocol.wasm > ${{ github.workspace }}/output/crypto.protocol.wasm.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            ${{ github.workspace }}/output/**
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@elacity-js'
      - run: |
          cd ${{ github.workspace }}/output
          sed -i "s/__VERSION__/${{steps.tag.outputs.tag}}/g" package.json
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}